# -*- coding: utf-8 -*-
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

L = "Limites de prestations (V. DCE 26/06/2026)"
GOC = "CCTP EIFFAGE (lot 02)"
GOD = "DPGF EIFFAGE (lot 02)"
SC = "CCTP SPK (ind. B, 20/03/2026)"
SD = "DPGF SPK (xls)"

R = [
# (gravité, type, sujet, doc A, doc B, constat, question / action, hypothèse planning)
("Haute","Double prestation","Démolition du radier existant",
 f"{L} §4 : démolition radier + évacuation = EIFFAGE. {GOD} 5.4.3.",
 f"{SC} 3.5.4 b : « démolition du radier et évacuation des gravats à la charge du présent lot ». {SD} 3.5 : « Démolition du radier béton existant (m²) ».",
 "Le même poste est chiffrable chez EIFFAGE et chez SPK.",
 "Confirmer EIFFAGE seul et retirer la ligne du DPGF SPK (ou l'inverse).",
 "Retenu chez EIFFAGE (tableau de limites)."),
("Haute","Double prestation","Radier neuf + fondations par pieux",
 f"{L} §4 : radier « P (définition) SPK / X (réalisation) EIFFAGE » ; pieux = EIFFAGE. {GOD} 5.5.1 et 5.5.5 ; {GOC} 5.5.",
 f"{SC} 3.5.4 b : radier béton « réalisé à charge du présent lot » (« fondation spéciale type pieux »). {SD} 3.5 : « Construction du nouveau radier béton… y compris fondation spéciale type pieux (m²) ».",
 "Radier et pieux sont chiffrés des deux côtés. Le CCTP SPK les rend conditionnels (« en fonction des conclusions du géotechnicien »), le CCTP EIFFAGE les rend fermes (G2PRO impose les pieux).",
 "Retirer la ligne radier/pieux du DPGF SPK ; SPK ne garde que la définition du principe (charges, platines, réservations).",
 "Retenu chez EIFFAGE."),
("Haute","Double prestation","Dépose de la cuve B2 existante",
 f"{L} §4 : dépose et évacuation réserve B = SPK. {GOC} 5.4.2 : « Par le lot sprinklage ».",
 f"{GOD} 5.4.2 : ligne « Dépose de la cuve source B2 » présente au DPGF EIFFAGE. {SD} 3.5 : « Déposer la réserve d'eau aérienne ».",
 "Une ligne existe dans le DPGF EIFFAGE alors que le CCTP EIFFAGE l'attribue à SPK.",
 "Neutraliser la ligne 5.4.2 du DPGF EIFFAGE (ou la remplacer par « sans objet »).",
 "Retenu chez SPK."),
("Haute","Double prestation","Tranchées communes (ouverture, remblaiement, finition)",
 f"{L} §5 : ouverture et remblaiement = EIFFAGE ; SPK = fourniture et pose des réseaux. {GOD} 5.6.1 (ml) ; {GOC} 5.6.1.",
 f"{SC} 3.5.4 et 3.5.5 : tranchée « réalisée par le présent lot, y compris remblaiement, finition espace vert et voirie lourde, grillage avertisseur ». {SD} 3.5 : « Réaliser une tranchée avec reprise de l'espace vert » (+ voirie lourde), 2 lignes (ml).",
 "Tranchée et remise en état chiffrées chez les deux lots.",
 "Retirer les 2 lignes « tranchée » du DPGF SPK (SPK = canalisations uniquement) ; corriger le CCTP SPK 3.5.4/3.5.5.",
 "Retenu : EIFFAGE ouvre/remblaie, SPK pose les réseaux."),
("Haute","Double prestation","Reprise espaces verts et voirie lourde au droit des tranchées",
 f"{L} §6 : enrobés, terrassements, terre végétale, gazon = EIFFAGE. {GOD} 5.10.",
 f"{SD} 3.5 : « reprise de l'espace vert et voirie lourde » dans les lignes tranchées. {SC} 3.5.4.",
 "Même remise en état chiffrée deux fois.",
 "À supprimer côté SPK avec la correction des tranchées (ligne ci-dessus).",
 "Retenu chez EIFFAGE."),
("Haute","Contradiction de périmètre","Fourreaux électriques et chambres de tirage",
 f"{L} §5 Électricité : ouverture tranchée + fourreau 2 × Ø90 = EIFFAGE ; chambre de tirage = EIFFAGE. {GOD} 5.6.4 et 5.6.5.",
 f"{SC} 3.5.5 : « Les fourreaux électriques… seront à la charge du présent lot, ainsi que les chambres de tirage ».",
 "Le CCTP SPK contredit le tableau de limites et le DPGF EIFFAGE.",
 "Aligner le CCTP SPK 3.5.5 sur le tableau de limites (EIFFAGE).",
 "Retenu chez EIFFAGE ; SPK tire les câbles."),
("Haute","Contradiction de périmètre","Gardiennage et surveillance du site",
 f"{SC} 1.21 : l'entreprise « devra prendre en charge tous les frais de gardiennage ». {SC} 3.1.4 : frais à sa charge si les réseaux ne sont pas remis en eau le week-end.",
 f"{SC} 3.1.5 : frais « prévus par le Maître d'Ouvrage à la demande de l'entreprise ». {L} §2 : gardiennage à charge du MO. {SD} 3.1.5 : ligne « Prestation de gardiennage » à chiffrer par SPK.",
 "Trois réponses différentes : SPK paie (1.21 et DPGF), MOA paie (3.1.5 et tableau).",
 "Trancher : MOA (tableau de limites) ou SPK ; supprimer la ligne DPGF si MOA. Préciser aussi le préavis de 5 semaines.",
 "Gardiennage prévu avec préavis de 5 semaines, payeur non figé."),
("Haute","Contradiction de périmètre","Compte prorata",
 f"{GOC} 5.11 et {GOD} : prorata 1,5 %, gestion par EIFFAGE. {GOC} 5.1.2, 5.1.7, 5.1.10 : éclairage, protections collectives, bennes en dépenses communes.",
 f"{SC} 1.3 et 1.19 : « lot unique… il n'y a pas de compte prorata ».",
 "Deux lots interviennent sur le chantier ; SPK se déclare « lot unique » sans prorata alors qu'EIFFAGE en gère un.",
 "Définir si SPK participe au prorata d'EIFFAGE (bennes, base vie, nettoyage).",
 "Sans effet sur le planning."),
("Moyenne","Double prestation","Ventilations haute et basse du local source A",
 f"{L} §4 : percement des voiles = EIFFAGE ; fourniture et pose des grilles = SPK. {GOC} 5.8.4 : percement « compris fourniture et pose des grilles de ventilation ».",
 f"{GOD} 5.8.4 (m²). {SD} 3.4.1 : « Ajouter des ventilations hautes et basses » (U).",
 "Les grilles sont attribuées à SPK par le tableau mais comprises dans le poste EIFFAGE par le CCTP 5.8.4.",
 "Préciser qui fournit et pose les grilles ; corriger le CCTP EIFFAGE 5.8.4 ou le DPGF SPK.",
 "Retenu : percement EIFFAGE, grilles SPK."),
("Moyenne","Double prestation","Scellements et calfeutrement coupe-feu (locaux B2 et GE)",
 f"{L} §4 : pose des pièces de scellement « et calfeutrement » = EIFFAGE. {GOC} 5.8.3 : reprise des parois, étanchéité.",
 f"{L} §4 : « Calfeutrement coupe-feu » = SPK (« seulement le rebouchage des nouvelles canalisations »). {SC} 1.11 : rebouchages à charge du lot qui perce.",
 "Frontière floue entre le calfeutrement de la pièce de scellement (EIFFAGE) et le rebouchage coupe-feu (SPK). Le CCTP SPK 3.4.2 dit aussi qu'un BET structure sera missionné par le MOA pour valider les scellements.",
 "Faire préciser par écrit : EIFFAGE = pièce scellée + étanchéité ; SPK = coupe-feu autour des tuyauteries.",
 "Retenu selon cette répartition."),
("Moyenne","Double prestation","Joint ciment périphérique de la cuve",
 f"{L} §4 : joint périphérique autour de la cornière = EIFFAGE. {GOD} 5.8.1 (ml) ; {GOC} 5.8.1.",
 f"{SC} 3.5.4 b : la liste des composants de la cuve inclut « un joint de propreté autour de la réserve ».",
 "Le joint figure à la fois dans la fourniture de la cuve (SPK) et dans le poste EIFFAGE.",
 "Confirmer EIFFAGE et retirer la mention du CCTP SPK.",
 "Retenu chez EIFFAGE."),
("Moyenne","Double prestation","Installation de chantier : clôture, panneau, base vie",
 f"{L} §1 : clôture, base vie (25 pers., 2 bungalows réunion) = SPK. {GOC} 5.1.3, 5.1.4, 5.1.9 : dus par le lot sprinklage.",
 f"{GOD} 5.1.3, 5.1.4, 5.1.9 : les trois lignes existent quand même au DPGF EIFFAGE.",
 "Lignes à chiffrer dans le DPGF EIFFAGE alors que le CCTP les attribue à SPK.",
 "Neutraliser 5.1.3, 5.1.4 et 5.1.9 du DPGF EIFFAGE.",
 "Retenu chez SPK."),
("Moyenne","Contradiction de périmètre","Branchements provisoires, armoire de chantier",
 f"{GOC} 5.1.6 : EIFFAGE doit les raccordements (eau, électricité, EU/EV) et « l'installation électrique pour ses besoins de chantier ».",
 f"{L} §1 : raccordement fluides de la base vie, armoire de chantier et point d'eau zone cuve = SPK. {SC} 1.19 : armoire provisoire + coffret de chantier.",
 "Deux armoires de chantier possibles ; périmètre des raccordements non tranché. Abonnements à la charge du MO (cohérent).",
 "Préciser si EIFFAGE s'alimente sur l'armoire SPK ou installe la sienne.",
 "Une seule armoire (SPK) retenue."),
("Moyenne","Contradiction de périmètre","Base vie : indépendante ou commune",
 f"{SC} 1.16 : base vie « de manière indépendante sur le parking de l'établissement ».",
 f"{L} §1 : base vie SPK « commune avec les autres lots ».",
 "Localisation et usage de la base vie non cohérents.",
 "Fixer l'emplacement (parking ou zone cuve) et la mutualisation.",
 "Base vie commune retenue."),
("Moyenne","Double prestation","Dévoiement des réseaux DN100 / DN150",
 f"{GOC} 5.6.1 : EIFFAGE « fera son affaire du supportage ou du dévoiement » des DN100 et DN150 croisant la tranchée, sans paiement séparé.",
 f"{GOC} 5.6.2 et {GOD} 5.6.2 : poste dédié de dévoiement des mêmes réseaux. {L} §1 : dévoiement incendie DN150 + AEP DN100 = EIFFAGE.",
 "Le même dévoiement est décrit comme inclus (5.6.1) et comme poste payé (5.6.2). Le réseau DN100 est « arrosage » au CCTP et « AEP » au tableau.",
 "Confirmer la nature du réseau DN100 (arrosage ou AEP) et la ligne de paiement.",
 "Une seule tâche (poste 5.6.2)."),
("Moyenne","Incohérence interne","Dépose du brise-vue, étêtage, purge et récolement des fondations",
 f"{L} §4 : dépose du brise-vue « y compris purge des fondations » ; étêtage à -1,00 m ; relevé géomètre et récolement (lignes fermes).",
 f"{GOC} 5.4.1 : pas de purge dans la dépose. {GOC} 5.4.4 et {GOD} 5.4.4 : purge à -80 cm en option.",
 "La purge apparaît de trois façons différentes (incluse, optionnelle, absente) ; l'étêtage à -1,00 m n'existe pas au CCTP.",
 "Définir une seule consistance : étêtage, récolement, purge (ferme ou option).",
 "Étêtage et récolement fermes ; purge en option."),
("Moyenne","Poste sans correspondance","Dévoiement EU / EV / EP / électricité / fibre / arrosage",
 f"{L} §1 : dévoiement « si nécessaire » = EIFFAGE (relevé NCA).",
 f"{GOD} 5.6.2 : seulement arrosage et incendie. Aucune ligne pour EU, EV, EP, électricité, fibre.",
 "Prestation conditionnelle sans ligne de prix.",
 "Créer une ligne en option ou provision au DPGF EIFFAGE.",
 "Tâche conditionnelle de 2 jours."),
("Moyenne","Double prestation","Dépose des réseaux existants entre cuve, local B2 et local GE",
 f"{L} §1 : dépose réseaux cuve B2 → locaux = EIFFAGE. {GOC} 5.6.3, {GOD} 5.6.3.",
 f"{L} §4 : « Dépose des réseaux existants local GE » = SPK. {SD} 3.5 : dépose GMPD et tuyauteries.",
 "Recouvrement aux extrémités (côté local) entre les deux lots.",
 "Fixer la limite au droit de la pièce de scellement.",
 "Limite à la paroi du local."),
("Moyenne","Doublon interne SPK","Armoires électriques (trois lignes)",
 f"{SD} 3.4.1 : armoire de répartition + disjoncteur depuis TGBT. {SD} 3.5 : armoire pompe jockey & source A + disjoncteur + câbles CR1.",
 f"{SD} 3.17 : armoire électrique dans le local source alimentant les équipements sprinkleurs.",
 "Trois lignes d'armoire pour un même local, périmètres qui se recoupent.",
 "Demander à ABSIX le schéma d'armoires (nombre exact).",
 "Trois tâches conservées."),
("Moyenne","Doublon interne SPK","Peinture, affichages, report d'alarmes, jockey et nourrices",
 f"{SD} 3.4.1 : reprise de la peinture des canalisations ; affichages/étiquetage (x2) ; sondes et contacts « reportés en alarme ».",
 f"{SD} 3.18 (peinture des réseaux) ; 3.22 (identification pochoir) ; 3.16 (report des alarmes créées). {SD} 3.5 : jockey « inclus avec le skid source A » + électropompe A « inclus nourrice » + dépose/remplacement des nourrices ({SC} 3.5.7).",
 "Même travail décrit à deux endroits ; risque de double chiffrage ou d'oubli.",
 "Demander à ABSIX de clarifier ce qui est inclus dans chaque ligne.",
 "Tâches distinctes conservées."),
("Moyenne","Doublon interne SPK","Feuilles 2027 et 2028 du DPGF SPK qui reprennent la Phase 1",
 f"{SC} 1.4 : Phase 1 = locaux, sources, postes de contrôle ; Phase 2 = postes 2, 3, 5, 6 ; Phase 3 = postes 1, 4, 7.",
 f"{SD}, onglets « Quantitatif 2027 » et « 2028 » : 88 lignes sur 97 identiques à la feuille 2026 (3.4.1 locaux, 3.5 sources, 3.6 postes), sans cellules de prix.",
 "Résidu de copier-coller : lignes de Phase 1 présentes en Phases 2 et 3. Le récapitulatif ne les compte qu'une fois.",
 "Faire supprimer ou griser ces lignes pour éviter un chiffrage multiple.",
 "Phase 1 uniquement."),
("Moyenne","Contradiction chiffrage","Provision pour travaux supplémentaires",
 f"{SC} 3.18 : provision de 5 % du montant HT, reliquat restitué au MOA.",
 f"{SD} 3.21 : « Provision (3% de la base H.T.) ».",
 "5 % au CCTP, 3 % au DPGF.",
 "Corriger l'un des deux documents.",
 "Sans effet sur le planning."),
("Moyenne","Contradiction de périmètre","Mesures compensatoires",
 f"{L} §2 : MOA « X » et SPK « X (P) ».",
 f"{SC} 3.1.4 et {SD} 3.1.4 : prévues et chiffrées par SPK seul.",
 "Le tableau fait participer le MOA, le CCTP et le DPGF non.",
 "Préciser la part MOA (renfort sécurité).",
 "Durée de la coupure B2 reprise dans le planning."),
("Moyenne","Contradiction de périmètre","Terre végétale",
 f"{L} §6 : « Apport de terre végétale… sur 0,30 m mini » = EIFFAGE.",
 f"{GOC} 2.6.1 : terre végétale « provenant du chantier » (reprise, mise en place, réglage) ; {GOD} 5.10.1 sans ligne d'apport.",
 "Apport extérieur ou réemploi de la terre du site ?",
 "Préciser, et créer la ligne d'apport au DPGF si nécessaire.",
 "Réemploi + apport prévus dans les tâches VRD."),
("Moyenne","Incohérence de désignation","« Local GE » / « local sprinklage » / « local source A + postes »",
 f"{L} §4 : « local GE » (dalle basse, pièce de scellement DN200). {GOC} 5.6.1 : « local Sprinklage » ; 5.8.5 : « Local sprinklage ».",
 f"{SC} 3.5.5 et {SD} 3.5 : « local source A + postes ». « Local GE » n'est défini ni au CCTP ni au DPGF SPK.",
 "Un même local porte trois noms (ou ce sont deux locaux différents).",
 "Faire confirmer que local GE = local source A + postes, plan à l'appui.",
 "Assimilés dans le planning."),
("Moyenne","Incohérence interne","Diamètres des canalisations B2",
 f"{L} §5 : « remplissage DN200 / retour essai DN150 », puis « remplissage/essai DN150 » (§4) ; « Vidange - EU DN200 ».",
 f"{SC} 3.5.4 b : remplissage/retour essai DN150 ; trop-plein DN150 ; vidange DN80.",
 "Remplissage DN200 ou DN150 selon la ligne du tableau ; le réseau EU DN200 alimente un trop-plein DN150.",
 "Vérifier sur le plan de principe ABSIX.",
 "Sans effet sur le planning."),
("Moyenne","Incohérence interne","Porte de l'enclos : grillagée ou pleine",
 f"{L} §4 : charpente + « porte grillagée » + bardage ; dépose « grille d'accès et porte grillagée ».",
 f"{GOC} 5.9.3 et {GOD} 5.9.3 : porte pleine en tôle 25/10, barre anti-panique, ferme-porte, 900 × 2100.",
 "Description de la nouvelle porte différente entre tableau et CCTP.",
 "Faire valider le type de porte.",
 "Porte pleine du CCTP retenue."),
("Moyenne","Incohérence interne","Puisard de trop-plein, regard EU et volume de la cuve",
 f"{GOC} 5.6.6 et {GOD} 5.6.6 : puisard de trop-plein attenant à la cuve (absent du tableau de limites).",
 f"{SC} 3.5.4 : cuve « sans puisard d'aspiration » ; regard 500 × 500 au droit du radier raccordé au réseau EU (à charge SPK). Volume : 620 m³ utile (3.5.4) et 625 m³ (« sans puisard »).",
 "Puisard (EIFFAGE) et regard (SPK) semblent désigner le même ouvrage ; le puisard n'a pas de ligne au tableau de limites ; deux volumes utiles.",
 "Confirmer l'ouvrage et son lot ; fixer le volume utile (620 ou 625 m³).",
 "Puisard chez EIFFAGE (CCTP 5.6.6)."),
("Moyenne","Incohérence technique","Classe du béton du radier et agressivité du sol",
 f"{GOC} 2.3.6 : infrastructures en C20/25 XC2 « à minima ».",
 f"{GOC} 4.4 : radier C25/30 XC2 XF1 ; 4.7.3 : classe d'agressivité < XA1 non reprise ; 4.1.3 : charge 5000 kg/m² « à confirmer avec le lot sprinklage ».",
 "Le radier est une infrastructure : C20/25 (2.3.6) ou C25/30 (4.4) ? Classe XA1 non traduite dans la formulation.",
 "Retenir C25/30 XC2 XF1 + exigence XA1 ; confirmer la charge avec SPK.",
 "Durcissement de 7 jours à valider avec le BET."),
("Moyenne","Contradiction de périmètre","Études béton et bureau d'études",
 f"{GOC} 3.2 et 5.2.4 : EIFFAGE réalise et paie les plans d'exécution béton, réseaux, élévations ; G3 à sa charge (5.2.5).",
 f"{SC} 3.5.4 : « les frais de l'étude de sol et de l'étude béton seront à la charge du MO ». {SC} 3.4.2 : BET structure missionné par le MOA pour valider les scellements.",
 "Étude béton à la charge du MO ou d'EIFFAGE ; BET structure MOA non cité côté EIFFAGE.",
 "Préciser qui produit les notes de calcul du radier et des scellements.",
 "Études hors planning EXE."),
("Faible","Contradiction de périmètre","Gestion des portails de chantier",
 f"{GOC} 5.1.3 : EIFFAGE gère les portails « jusqu'à l'achèvement des travaux TCE ».",
 f"{L} §1 : EIFFAGE en phase 1, SPK en phases 2 et 3, « sur la durée des travaux de chaque lot ».",
 "Durée de la mission d'EIFFAGE différente.",
 "Aligner le CCTP sur le tableau.",
 "Du début à la fin de la Phase 1."),
("Faible","Poste sans correspondance","Postes absents d'un des documents",
 f"{L} : drain périphérique du radier (si G2PRO) ; curage + contrôle caméra des EU ; homme trafic « chacun pour son lot » ; relevé géomètre/récolement.",
 f"{GOD} : pas de ligne drain ni curage/caméra ; {SD} : pas de ligne homme trafic ; {GOC} 2.6 : entretien du gazon (12 fauchages, année de garantie, contrat d'entretien) sans ligne au DPGF.",
 "Prestations décrites mais sans poste de prix correspondant.",
 "Ajouter les lignes ou les déclarer incluses.",
 "Tâches présentes dans le planning."),
("Faible","Poste sans correspondance","Postes SPK présents dans un seul document",
 f"{SC} 3.6.1 : « installation d'un indicateur de passage d'eau sur le PC n°5 » (protection du local sprinkleur).",
 f"{SD} 3.4.1 : « Ajouter protection sprinkleur dans gaine technique (Remarque Q1) » n'apparaît pas dans la liste du CCTP 3.4.1 ; l'indicateur PC5 n'a pas de ligne au DPGF.",
 "Écart entre liste CCTP et lignes DPGF.",
 "Faire compléter le DPGF et le CCTP.",
 "Les deux ont été intégrés au planning."),
("Faible","Contradiction chiffrage","Plus-value nuit et gardiennage nuit en Phase 1",
 f"{SC} 1.21 : travaux de jour (7 h à 20 h) dans les locaux techniques ; nuit pour les zones publiques.",
 f"{SD} 3.1.5 (feuille 2026) : gardiennage de nuit et « plus value travaux de nuit » chiffrés pour la Phase 1.",
 "Phase 1 = locaux techniques et sources, donc travail de jour.",
 "Confirmer les interventions de nuit (vidanges, raccordements) ; sinon retirer.",
 "Travail de jour retenu."),
("Faible","Numérotation","Numéros du DPGF SPK décalés par rapport au CCTP",
 f"{SC} : 3.10 remarques, 3.11 point F, 3.15 alarmes, 3.16 électricité, 3.17 peinture, 3.18 provision, 3.20 essais, 3.21 options.",
 f"{SD} : 3.11 remarques, 3.12 point F, 3.16 alarmes, 3.17 électricité, 3.18 peinture, 3.21 provision, 3.22 essais, 3.23.1 options.",
 "Références croisées CCTP ↔ DPGF fausses à partir de 3.10.",
 "Mettre à jour la numérotation.",
 "Aucun."),
("Faible","Identification","Titres, lots, adresses et dates",
 f"{GOC} et {GOD} : « révision trentenaire » ; {GOD} : onglet « LOT 08 » mais « Lot 02 » dans le titre ; adresse « 8 Boulevard de Mons ».",
 f"{SC}, {L} : « révision majeure » ; adresse « 4 boulevard de Mons ». Dates : DPGF EIFFAGE 15/06/2026, tableau « DCE 26/06/2026 » édité le 07/07/2026, CCTP EIFFAGE juillet 2026, CCTP SPK 20/03/2026 ind. B.",
 "Intitulés et références non harmonisés entre les pièces.",
 "Harmoniser avant diffusion aux entreprises.",
 "Aucun."),
("Faible","Interprétation","Tableau de limites : colonnes VRD et GO séparées",
 f"{L} : titre « lots SPRINKLAGE / GO / CM / BARDAGE / VRD » avec colonnes V.R.D. et GO/CM/Bardage distinctes.",
 f"{GOC} : « Lot n°02 – VRD – GROS ŒUVRE – BARDAGE – ESPACES VERTS » : un seul lot.",
 "Le tableau laisse croire à deux lots ; certaines lignes sont réparties entre les deux colonnes.",
 "Fusionner les colonnes en une seule (EIFFAGE).",
 "Un seul lot EIFFAGE, comme demandé."),
]

wb = openpyxl.Workbook(); ws = wb.active; ws.title = "Incohérences"
hdr = ["N°", "Gravité", "Type", "Sujet", "Document A", "Document B / contradiction", "Constat", "Question / action proposée", "Hypothèse retenue dans le planning"]
ws.append(["Phase 1 DECATHLON CAMPUS : incohérences relevées entre tableau de limites, CCTP et DPGF (EIFFAGE et SPK)"])
ws.append(["Gravité : Haute = même prestation chez 2 lots ou contradiction financière ; Moyenne = périmètre flou ou doublon ; Faible = écart de forme ou poste à compléter."])
ws.append([]); ws.append(hdr)
fills = {"Haute": "F4B6B0", "Moyenne": "FCE3B0", "Faible": "DCEBD3"}
thin = Side(style="thin", color="BBBBBB")
for i, r in enumerate(R, 1):
    ws.append([i] + list(r))
for c in ws[4]:
    c.font = Font(bold=True, color="FFFFFF"); c.fill = PatternFill("solid", fgColor="1F2A44"); c.alignment = Alignment(wrap_text=True, vertical="center")
for row in ws.iter_rows(min_row=5):
    for c in row:
        c.alignment = Alignment(wrap_text=True, vertical="top"); c.border = Border(top=thin, bottom=thin, left=thin, right=thin)
    row[1].fill = PatternFill("solid", fgColor=fills[row[1].value]); row[1].font = Font(bold=True)
ws["A1"].font = Font(bold=True, size=13); ws["A2"].font = Font(italic=True)
for i, w in enumerate((5, 10, 20, 32, 60, 60, 48, 42, 30), 1): ws.column_dimensions[get_column_letter(i)].width = w
ws.freeze_panes = "E5"; ws.auto_filter.ref = "A4:I%d" % (4 + len(R))
wb.save("/home/user/LeSacdOr/planning/Registre_incoherences_Phase1.xlsx")
import collections; print(len(R), collections.Counter(r[0] for r in R))
